### ISSUE TITLE
Miner stopped

### ISSUE THREAD

**Issue by yttalium** [richardhyy/EusMinerHat#4]
Hello, when I start the miner he stopped ~1 minute after.

https://www.casimages.com/i/210603110501973457.jpg.html

**Comment by richardhyy** [comment]
Sorry for delayed reply. :(

This is probably caused by auto check timer. You can either make the `miningPlayerCountCeiling` in the policy higher, or set `checkIntervalSeconds` to `0` in the config.yml.

**Comment by yttalium** [comment]
No problem, I close the ticket because the miner restart automatically but I'm going to try your solution ;)

**Comment by richardhyy** [comment]
> No problem, I close the ticket because the miner restart automatically but I'm going to try your solution ;)

but please note, by setting `checkIntervalSeconds` to 0, the miner can only be manually started and stopped, and this is not the plugin was designed for. It is created to take advantage of the spared server time without deteriorating players' experience while still make profits for the server owner.

**Comment by yttalium** [comment]
I edit it, I will warn you if I see a another problem

**Comment by yttalium** [comment]
No more problem, thanks.
I wish your plugin became better in the futur.
I make a rate tomorrow :D
